//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Publicacion()
        {
            this.Registro = new HashSet<Registro>();
        }
    
        public int idPublicacion { get; set; }
        public string NombrePublicacion { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public string Descripcion { get; set; }
        public bool estatus { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idTipoPublicacion { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoPublicacion TipoPublicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
    }
}
