//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int idRegistro { get; set; }
        public string FechaRegistro { get; set; }
        public string Observaciones { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idPublicacion { get; set; }
        public bool estatus { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
