//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPeriodico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolOperacion
    {
        public int idRolOperacion { get; set; }
        public int idTipoUsuario { get; set; }
        public int idOperacion { get; set; }
        public bool Estatus { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
